# ===========================================
# SERVICE - Expõe o SQL Server internamente
# ===========================================
# Cria um endpoint DNS interno para o banco de dados
# Outros pods podem conectar usando: sqlserver-service:1433

apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: vehicle-resale
  labels:
    app: sqlserver
spec:
  # Seletor - roteia tráfego para pods com label app=sqlserver
  selector:
    app: sqlserver
  
  # Portas do serviço
  ports:
    - port: 1433        # Porta do serviço
      targetPort: 1433  # Porta do container
      protocol: TCP
      name: sql
  
  # Tipo do serviço - ClusterIP = apenas interno
  type: ClusterIP
  
  # ClusterIP estático (opcional)
  # clusterIP: None  # Para StatefulSet (headless service)