# ===========================================
# DEPLOYMENT - SQL Server Database
# ===========================================
# Define como o SQL Server será executado no cluster
# Inclui configurações de recursos, volumes e variáveis

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: vehicle-resale
  labels:
    app: sqlserver
    tier: database
spec:
  # Réplicas - SQL Server Express suporta apenas 1 réplica
  replicas: 1
  
  # Seletor para identificar os pods
  selector:
    matchLabels:
      app: sqlserver
  
  # Template do Pod
  template:
    metadata:
      labels:
        app: sqlserver
        tier: database
    spec:
      containers:
        - name: sqlserver
          # Imagem do SQL Server 2022
          image: mcr.microsoft.com/mssql/server:2022-latest
          
          # Porta do SQL Server
          ports:
            - containerPort: 1433
              name: sql
          
          # Variáveis de ambiente
          env:
            - name: ACCEPT_EULA
              value: "Y"
            
            # Senha do SA vinda do Secret
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vehicle-resale-secrets
                  key: sa-password
            
            # Edição do SQL Server
            - name: MSSQL_PID
              value: "Express"  # Developer para desenvolvimento, Standard/Enterprise para produção
          
          # Montagem do volume persistente
          volumeMounts:
            - name: sqlserver-storage
              mountPath: /var/opt/mssql
          
          # Recursos do container
          resources:
            # Mínimo garantido
            requests:
              memory: "1Gi"    # 1GB RAM mínimo
              cpu: "500m"      # 0.5 CPU
            # Máximo permitido
            limits:
              memory: "2Gi"    # 2GB RAM máximo
              cpu: "1000m"     # 1 CPU
          
          # Probes de saúde (opcional)
          # livenessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q "SELECT 1"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
      
      # Volumes do Pod
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: sqlserver-pvc